Project K12_finances {
  database_type: 'MySQL'
  Note: '''
    Combines data from:
    * U.S. Census Bureau (census.gov)
    * U.S. Department of Education (ed.gov)
       * National Center for Education Statistics (NCES) (nces.ed.gov)
    * New York State Education Department (nysed.gov)
    
    ### Census data
    * GIS counties
    * GIS unified school districts
    * [calculated] GIS county/unified school district intersections
    * SAIPE - Small Area Income and Poverty Estimates  
    * ASSSF - Annual Survey of School System Finances

    ### NCES data
    * CWIFT - Comparable Wage Index for Teachers
  '''
}

// **************************************************************************************
//// 
//// Census GIS (TIGER) 
//// https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2020.html
////
// **************************************************************************************

// **************************************************************************************
// GIS counties
// **************************************************************************************

// tl_2020_36_county
Table census_gis_counties {
  STATEFP varchar(2) [note: '''
    Current state FIPS code\
    36 = NY
    ''']
  COUNTYFP varchar(3) [note: '''
    Current county FIPS code
    e.g. 001 = Albany County''']
  COUNTYNS varchar(8) [note: 'ANSI feature code for the county or equivalent feature 
e.g. 00974099 = Albany County']
  GEOID  varchar(5) [pk, note: 'County identifier; a concatenation of Current state FIPS code and county FIPS code
e.g. 36001 = Albany County']
  NAME  varchar(100) [note: 'Current county name
e.g. Albany']
  NAMELSAD  varchar(100) [note: 'Current name and the translated legal/statistical area description for county
e.g. Albany County']
  LSAD varchar(2) [note: 'Current legal/statistical area description code for county
e.g. 06 = County (suffix)']
  CLASSFP varchar(2) [note: 'Current FIPS class code
e.g. H1 = An active county or equivalent feature']
  MTFCC varchar(5) [note: 'MAF/TIGER Feature Class Code
G4020 = County or Equivalent Feature']
  CSAFP varchar(3) [note: 'Current combined statistical area code 
e.g. 104 = Albany-Schenectady, NY']
  CBSAFP  varchar(5) [note: 'Current metropolitan statistical area/micropolitan statistical area code
e.g. 10580 = Albany-Schenectady-Troy, NY']
  METDIVFP varchar(5) [note: 'Current metropolitan division code
NULL']
  FUNCSTAT varchar(1) [note: 'Current functional status
e.g. A = Active government providing primary general-purpose functions']
  ALAND numeric(14) [note: 'Current land area in square meters
e.g. 1354273421']
  AWATER numeric(14) [note: 'Current water area in square meters
e.g. 26971925']
  INTPTLAT varchar(11) [note: 'Current latitude of the internal point
e.g. +42.5882401']
  INTPTLON varchar(12) [note: 'Current longitude of the internal point
e.g. -073.9740095']

  note: 'Geographic information about counties'
}

// **************************************************************************************
// GIS unified school districts
// **************************************************************************************

// tl_2020_36_unsd
Table census_gis_unified_school_districts {
  STATEFP varchar(2) [note: 'Current state FIPS code
36 = NY']
  UNSDLEA varchar(5) [note: 'Current unified school district local education agency code
e.g. 02460 = Albany City School District']
  GEOID varchar(7) [pk, note: 'School district identifier; a concatenation of the current state FIPS code and the unified school district local education agency code
e.g. 3602460 = Albany City School District']
  NAME varchar(100) [note: 'Current unified school district name
e.g. Albany City School District']
  LSAD varchar(2) [note: 'Current legal/statistical area description code for unified school district
e.g. 00']
  LOGRADE varchar(2) [note: 'Current lowest grade covered by school district
e.g. PK']
  HIGRADE varchar(2) [note: 'Current highest grade covered by school district
e.g. 12']
  MTFCC varchar(5) [note: 'MAF/TIGER Feature Class Code
G5420 = Unified School District']
  SDTYP varchar(1) [note: 'Current school district type
e.g. NULL']
  FUNCSTAT varchar(1) [note: 'Current functional status
e.g. E = Active government providing special-purpose functions']
  ALAND numeric(14) [note: 'Current land area in square meters
e.g. 55435357']
  AWATER numeric(14) [note: 'Current water area in square meters
e.g. 1377120']
  INTPTLAT varchar(11) [note: 'Current latitude of the internal point
e.g. +42.6657453']
  INTPTLON varchar(12) [note: 'Current longitude of the internal point
e.g. -073.7983532']

  note: 'Geographic information about unified school districts'
}

// **************************************************************************************
// [calculated] GIS county/unified school district intersections
// **************************************************************************************

// county/unsd intersection
Table census_gis_county_unsd_intersect {
  INTERSECT_ID varchar(13) [pk, note: 'Intersect identifier; a concatenation of COUNTY_GEOID-UNSD_GEOID
e.g. 36001-3602460 = Intersection of Albany County and Albany City School District ']
  COUNTY_GEOID varchar(5) [note: 'County identifier; a concatenation of Current state FIPS code and county FIPS code
e.g. 36001 = Albany County']
  UNSD_GEOID varchar(7) [note: 'School district identifier; a concatenation of the current state FIPS code and the unified school district local education agency code
e.g. 3602460 = Albany City School District']
  INTERSECT_AREA_IN_SQ_METERS double [note: 'Intersection area in square meters. (Geometry attribute via QGIS)
e.g. 62956978.38 ']
  INTERSECT_AREA_IN_SQ_MILES double [note: 'Intersection area in square miles. Calculated as INTERSECT_AREA_IN_SQ_METERS / 1000000 * 2.58998811
e.g. 62956978.38 ']
  INTERSECT_PERIMETER double [note: 'Intersection perimeter in meters (Geometry attribute via QGIS)
e.g. 55139.73854 ']

  note: 'Geographic information about how counties and unified school districts intersect'
}

Ref: census_gis_county_unsd_intersect.COUNTY_GEOID > census_gis_counties.GEOID
Ref: census_gis_county_unsd_intersect.UNSD_GEOID > census_gis_unified_school_districts.GEOID

// **************************************************************************************
//// 
//// Census Surveys and Programs
//// https://www.census.gov/programs-surveys.html
////
// **************************************************************************************

// **************************************************************************************
// SAIPE
// **************************************************************************************

Table census_saipe_sd {
  STATEFP varchar(2) [note: 'FIPS State Code (00 for US record)
36 = NY']
  DISTRICT_ID varchar(5) [note: 'District ID
e.g. 02460 = Albany City School District']
  CALC_GEOID varchar(7) [pk, note: 'Calculated field: STATEFP || DISTRICT_ID
e.g. 3602460 = Albany City School District']
  DISTRICT_NAME varchar(100) [note: 'District Name
e.g. Albany City School District']
  TOTAL_POP numeric(8) [note: 'Total Population']
  POP_CHILD numeric(8) [note: 'Population of Relevant Children 5 to 17 years of Age']
  EST_CHILD_POV numeric(8) [note: 'Estimated Number of Relevant Children 5 to 17 years old in Poverty Related to the Householder']
  FILENAME_DATE varchar(21) [note: 'A tag indicating the file name and date of creation']
  
  note: 'Small Area Income and Poverty Estimates (SAIPE) Program data by school district'
}

Ref: census_saipe_sd.CALC_GEOID > census_gis_unified_school_districts.GEOID

Table census_saipe_county {
  STATEFP varchar(2) [note: 'FIPS State code (00 for US record)']
  COUNTYFP varchar(3) [note: 'FIPS county code ( 0 for US or state level records)']
  CALC_GEOID varchar(5) [pk, note: 'Calculated field: STATEFP || COUNTYFP']
  EST_CNT_ALL_POV varchar(8) [note: 'Estimate of people of all ages in poverty']
  EST_CNT_ALL_POV_90L varchar(8) [note: '90% confidence interval lower bound of estimate of people of all ages in poverty']
  EST_CNT_ALL_POV_90U varchar(8) [note: '90% confidence interval upper bound of estimate of people of all ages in poverty']
  EST_PCT_ALL_POV varchar(4) [note: 'Estimated percent of people of all ages in poverty']
  EST_PCT_ALL_POV_90L varchar(4) [note: '90% confidence interval lower bound of estimate of percent of people of all ages in poverty']
  EST_PCT_ALL_POV_90U varchar(4) [note: '90% confidence interval upper bound of estimate of percent of people of all ages in poverty']
  EST_CNT_017_POV varchar(8) [note: 'Estimate of people age 0-17 in poverty']
  EST_CNT_017_POV_90L varchar(8) [note: '90% confidence interval lower bound of estimate of people age 0-17 in poverty']
  EST_CNT_017_POV_90U varchar(8) [note: '90% confidence interval upper bound of estimate of people age 0-17 in poverty']
  EST_PCT_017_POV varchar(4) [note: 'Estimated percent of people age 0-17 in poverty']
  EST_PCT_017_POV_90L varchar(4) [note: '90% confidence interval lower bound of estimate of percent of people age 0-17 in poverty']
  EST_PCT_017_POV_90U varchar(4) [note: '90% confidence interval upper bound of estimate of percent of people age 0-17 in poverty']
  EST_CNT_517_POV varchar(8) [note: 'Estimate of related children age 5-17 in families in poverty']
  EST_CNT_517_POV_90L varchar(8) [note: '90% confidence interval lower bound of estimate of related children age 5-17 in families in poverty']
  EST_CNT_517_POV_90U varchar(8) [note: '90% confidence interval upper bound of estimate of related children age 5-17 in families in poverty']
  EST_PCT_517_POV varchar(4) [note: 'Estimated percent of related children age 5-17 in families in poverty']
  EST_PCT_517_POV_90L varchar(4) [note: '90% confidence interval lower bound of estimate of percent of related children age 5-17 in families in poverty']
  EST_PCT_517_POV_90U varchar(4) [note: '90% confidence interval upper bound of estimate of percent of related children age 5-17 in families in poverty']
  EST_MED_INC varchar(6) [note: 'Estimate of median household income']
  EST_MED_INC_90L varchar(6) [note: '90% confidence interval lower bound of estimate of median household income']
  EST_MED_INC_90U varchar(6) [note: '90% confidence interval upper bound of estimate of median household income']
  COUNTY_NAME varchar(100) [note: 'State or county name']
  STATE_POSTAL varchar(2) [note: 'Two-letter Postal State abbreviation']
  FILENAME_DATE varchar(22) [note: 'A tag indicating the file name and date of creation']  
  note: 'Small Area Income and Poverty Estimates (SAIPE) Program data by county'
}

Ref: census_saipe_county.CALC_GEOID > census_gis_counties.GEOID

// **************************************************************************************
// Annual Survey of School System Finances
// **************************************************************************************
Table census_asssf_unit_tables {
  IDCENSUS varchar(14) [note: 'School System Identification Number; a concatenation of STATECODE (NOT FIPS), GOVTYPE_CODE, COUNTYFP, and others']
  NAME     varchar(100) [note: 'School System Name']
  CONUM    varchar(5) [note: 'ANSI State and County Code (FIPS)']
  CSA      varchar(3) [note: 'Consolidated Statistical Area']
  CBSA     varchar(5) [note: 'Core-Based Statistical Area']
  NCESID   varchar(7) [pk, note: 'NCES Identification Number'] 
  ENROLL   integer [note: 'Fall Membership']
  TOTALREV integer [note: 'TOTAL ELEMENTARY-SECONDARY REVENUE (thousands of dollars)']
  TFEDREV  integer [note: 'Total Revenue from Federal Sources']
  FEDRCOMP integer [note: '  Compensatory (Title I)']
  FEDRSPEC integer [note: '  Children with disabilities']
  FEDRNUTR integer [note: '  Child Nutrition Act']
  FEDROTHR integer [note: '  All other federal aid']
  TSTREV   integer [note: 'Total Revenue from State Sources']
  STRFORM  integer [note: '  General formula assistance']
  STRSPEC  integer [note: '  Special education programs']
  STRTRANS integer [note: '  Transportation programs']
  STROTHR  integer [note: '  All other state revenue']
  TLOCREV  integer [note: 'Total Revenue from Local Sources']
  LOCRTAX  integer [note: '  All taxes']
  LOCRPROP integer [note: '  Property taxes']
  LOCRPAR  integer [note: '  Parent government contributions']
  LOCRCICO integer [note: '  Revenue from cities and counties']
  LOCROSCH integer [note: '  Revenue from other school systems']
  LOCRCHAR integer [note: '  Charges']
  LOCROTHR integer [note: '  Other local revenues']
  TOTALEXP integer [note: 'TOTAL ELEMENTARY-SECONDARY EXPENDITURE (thousands of dollars)']
  TCURSPND integer [note: '  Total Current Spending']
  TSALWAGE integer [note: '    Total salaries and wages']
  TEMPBENE integer [note: '    Total employee benefit payments']
  TCURINST integer [note: '  Total Current Spending for Instruction']
  TCURISAL integer [note: '    Salaries and wages for instruction']
  TCURIBEN integer [note: '    Employee benefits for instruction']
  TCURSSVC integer [note: '  Total Current Spending for Support Services']
  TCURSPUP integer [note: '    Pupil support']
  TCURSSTA integer [note: '    Instructional staff support']
  TCURSGEN integer [note: '    General administration']
  TCURSSCH integer [note: '    School administration']
  TCURSOTH integer [note: '    Other and nonspecified']
  TCURONON integer [note: '  Other Current Spending']
  TCAPOUT  integer [note: '  Total Capital Outlay Expenditure']
  TPAYOTH  integer [note: '  Payments to Other Governments']
  TINTRST  integer [note: '  Interest on School System Indebtedness']
  DEBTOUT  integer [note: '  Long-term debt outstanding at end of the fiscal year']
  LONGISSU integer [note: '  Long-term debt issued during the fiscal year']
  LONGRET  integer [note: '  Long-term debt retired during the fiscal year']
  PCTTOTAL double  [note: 'PERCENT - TOTAL ELEMENTARY-SECONDARY REVENUE']
  PCTFTOT  double  [note: '  Percent - Total Revenue from Federal Sources']
  PCTFCOMP double  [note: '  Percent - Compensatory (Title I)']
  PCTSTOT  double  [note: '  Percent - Total Revenue from State Sources']
  PCTSFORM double  [note: '  Percent - General formula assistance']
  PCTLTOT  double  [note: '  Percent - Total Revenue from Local Sources']
  PCTLTAXP double  [note: '  Percent - Taxes and parent government contributions']
  PCTLOTHG double  [note: '  Percent - Revenue from other local governments']
  PCTLCHAR double  [note: '  Percent - Charges']
  PPCSTOT  integer [note: 'PER PUPIL - TOTAL CURRENT SPENDING (ELEMENTARY-SECONDARY)']
  PPSALWG  integer [note: '  Per Pupil - Total salaries and wages']
  PPEMPBEN integer [note: '  Per Pupil - Total employee benefit payments']
  PPITOTAL integer [note: '  Per Pupil - Total Current Spending for Instruction']
  PPISALWG integer [note: '  Per Pupil - Salaries and wages']
  PPIEMBEN integer [note: '  Per Pupil - Employee benefits']
  PPSTOTAL integer [note: '  Per Pupil - Total Current Spending for Support Services']
  PPSPUPIL integer [note: '  Per Pupil - Pupil support']
  PPSSTAFF integer [note: '  Per Pupil - Instructional staff support']
  PPSGENAD integer [note: '  Per Pupil - General administration']
  PPSSCHAD integer [note: '  Per Pupil - School administration']
  GOVTYPE_CODE char(1) [note: 'The 3rd character from IDCENSUS']
  GOVTYPE_DESC varchar(100) [note: 'Lookup value from p.26 of school20doc']
  DEPENDENT_ID varchar(5) [note: 'State FIPS code; characters 1-2 of CONUM']
  STATEFP char(2) [note: 'State FIPS code; characters 1-2 of CONUM']
  COUNTYFP char(3) [note: 'County FIPS code; characters 3-5 of CONUM']
  note: 'Individual unit data from Census Annual Survey of School System Finances'
}

Ref: census_asssf_unit_tables.NCESID > census_gis_unified_school_districts.GEOID
Ref: census_asssf_unit_tables.CONUM > census_gis_counties.GEOID

// **************************************************************************************
//// 
//// NCES
//// https://nces.ed.gov
////
// **************************************************************************************

// **************************************************************************************
// Comparable Wage Index for Teachers - School Districts (EDGE_ACS_CWIFT_2019_LEA_1920.txt)
// **************************************************************************************
Table nces_cwift_lea {
  LEAID    varchar(7) [pk, note: 'STATE FIPS || 5-digit LEA CODE']
  NAME     varchar(100) [note: 'Local Education Agency Name']
  ST_NAME  varchar(100) [note: 'State Name']
  LEA_CWIFTEST      varchar(3) [note: 'CWIFT estimate for each LEA (divide dollars by this to get normalized amounts)']
  LEA_CWIFTSE     varchar(5) [note: 'CWIFT standard error for each LEA']
  note: 'NCES Comparable Wage Index for Teachers data (based on Census ACS data)'
}

Ref: nces_cwift_lea.LEAID > census_gis_unified_school_districts.GEOID

// **************************************************************************************
//// 
//// NYSED
//// https://data.nysed.gov/downloads.php
////
// **************************************************************************************

// **************************************************************************************
// NYSED/LEA crosswalk
// NYSED uses BEDS codes which don't match to the rest of the data from NCES and Census
// **************************************************************************************
Table xwalk_nysed_lea {
  DISTRICT_CD       varchar(8)   [pk, note: '8-digit code of school district']
  DISTRICT_NAME     varchar(255) [note: 'Name of school district']
  ENTITY_NAME       varchar(255) [note: 'Name of district, public school, or charter school']
  LEA_GEOID         varchar(7)   [note: 'STATE FIPS || 5-digit LEA CODE']
  LEA_NAME          varchar(100) [note: 'Name from census_gis_unified_school_districts']
  NONMATCHED_NOTES  varchar(255) [note: 'Notes about why a district was not able to be matched to a LEA_GEOID']
  note: 'Crosswalk table to match NYSED DISTRICT_CD with GEOID/NCESID'
}

Ref: xwalk_nysed_lea.LEA_GEOID > census_gis_unified_school_districts.GEOID

// **************************************************************************************
// Student and Educator database - Staff table
// **************************************************************************************
Table nysed_studed_staff {
  ENTITY_CD     varchar(12) [pk, note: '12-digit BEDS code for district, public school, and charter school']
  ENTITY_NAME   varchar(255) [note: 'Name of district, public school, or charter school']
  YEAR          integer [pk, note: 'School Year (2018 for 2017-18, 2019 for 2018–19, and 2020 for 2019-20). ']
  DISTRICT_CD   varchar(8) [note: '8-digit code of school district']
  DISTRICT_NAME varchar(255) [note: 'Name of school district']
  CSO_NAME      varchar(255) [note: 'School principal name']
  STREET        varchar(255) [note: 'School mailing address']
  CITY          varchar(255) [note: 'School city address']
  PHONE         varchar(255) [note: 'School telephone number']
  GRADE_RANGE   varchar(255) [note: 'Range of grades in the entity from low to high']
  NUM_PRINC     double [note: 'Total number of principals']
  NUM_TEACH     double [note: 'Total number of teachers']
  NUM_COUNSELORS double [note: 'Total number of school counselors']
  NUM_SOCIAL     double [note: 'Total number of social workers']
  PER_ATTEND     double [note: 'Percent of teachers in attendance']
  PER_TURN_FIVE_YRS double [note: 'Turnover rate of teachers with fewer than five years of experience']
  PER_TURN_ALL double [note: 'Turnover rate of all teachers']
  note: 'Staff data from NYSED Student and Educator database'
}

Ref: nysed_studed_staff.DISTRICT_CD > xwalk_nysed_lea.DISTRICT_CD



// **************************************************************************************
// DBML Reference reminder
// **************************************************************************************
// Creating references
// You can also define relaionship separately
// > many-to-one; < one-to-many; - one-to-one; <> many-to-many
// Ref: U.country_code > countries.code  
// Ref: ecommerce.merchants.country_code > countries.code
// **************************************************************************************
